### ISSUE TITLE
Add documentation to detail docker run command

### ISSUE THREAD

**Issue by AngelOnFira** [actions/container-action#3]
It is not documented how the run command is used when a Github Action is executed.

In my particular use case, I wanted to figure out how to get files off a container Action. The answer is to send any output files to `/github/workspace`. It would be helpful to see that somewhere in the documentation.

Having some more information about the rest of the commands would be useful as well I think.

```
/usr/bin/docker run
    --name <hash> \
    --label <hash> \
    --workdir /github/workspace \
    --rm \
    -e HOME \
    -e GITHUB_REF \
    -e GITHUB_SHA \
    -e GITHUB_REPOSITORY \
    -e GITHUB_ACTOR \
    -e GITHUB_WORKFLOW \
    -e GITHUB_HEAD_REF \
    -e GITHUB_BASE_REF \
    -e GITHUB_EVENT_NAME \
    -e GITHUB_WORKSPACE \
    -e GITHUB_ACTION \
    -e GITHUB_EVENT_PATH \
    -e RUNNER_OS \
    -e RUNNER_TOOL_CACHE \
    -e RUNNER_TEMP \
    -e RUNNER_WORKSPACE \
    -v "/var/run/docker.sock":"/var/run/docker.sock" \
    -v "/home/runner/work/_temp/_github_home":"/github/home" \
    -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
    -v "/home/runner/work/sauce/sauce":"/github/workspace" \
    <hash>
```

**Comment by ncalteen** [comment]
Hello! Apologies for the delay in responding to your issue. I've tracked down a few documentation sources that may be helpful.

- Regarding the environment variables that are set, the documentation for their usage can be found [here](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).
- As you have seen, the local directory on the runner, `$GITHUB_WORKSPACE` (`/home/runner/work/sauce/sauce` in this case), maps to the `/github/workspace` directory on the running container. I have submitted [this PR](https://github.com/github/docs-internal/pull/41827) to the GitHub documentation to mention this!

**Comment by ncalteen** [comment]
Hello again! This has been added to the documentation here: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#accessing-files-created-by-a-container-action

I'll close this out for now, but if you have other questions please feel free to comment and reopen!
