### ISSUE TITLE
Support Windows agents

### ISSUE THREAD

**Issue by galvesribeiro** [actions/container-action#4]
Hello,

When I try to run a container action or to create my own and invoke a container, it fails saying that it is only supported on Linux agents.

Any ideas when windows will be supported?

I can run `docker run` just fine from a Windows agent...

Thank you!

**Comment by ncalteen** [comment]
Hello! Apologies for the delay in responding to this issue. Currently this looks to be a feature in the [`actions/runner` backlog](https://github.com/actions/runner/issues/1402). It would be best to track from there, since this would be an enhancement to that service.
